services:
    app:
        image: wolfsmind/cardgame:latest
        build:
          context: .
          dockerfile: ./Dockerfile
        environment:
          - ASPNETCORE_URL=http://*:5000
        ports: 
            - "5000:80"
        links:
            - db:db
        depends_on:
            - db
        restart: always

    db:
      image: postgres:14.1-alpine
      restart: always
      environment:
        - POSTGRES_DB=CardGameDb
        - POSTGRES_USER=systemUser
        - POSTGRES_PASSWORD=systemPassword
      ports:
        - '5432:5432'
      volumes: 
        - ./postgres-data:/var/lib/postgresql/data