// <auto-generated />
using System;
using System.Collections.Generic;
using CardGame.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CardGame.Database.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20230618065105_UpdatePileModel")]
    partial class UpdatePileModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CardGame.Domain.Models.Card", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Card_Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Name");

                    b.Property<string>("Signature")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Signature");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Value");

                    b.HasKey("Id");

                    b.ToTable("Card");
                });

            modelBuilder.Entity("CardGame.Domain.Models.Deck", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Deck_Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DiscardPile")
                        .HasColumnType("integer")
                        .HasColumnName("Discard_Pile");

                    b.Property<int>("DrawPile")
                        .HasColumnType("integer")
                        .HasColumnName("Draw_Pile");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("Is_Active");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("Last_Modified");

                    b.HasKey("Id");

                    b.ToTable("deck");
                });

            modelBuilder.Entity("CardGame.Domain.Models.Pile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Pile_Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<List<string>>("Cards")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("Cards");

                    b.Property<bool>("IsDiscardPile")
                        .HasColumnType("boolean")
                        .HasColumnName("Is_Discard_Pile");

                    b.Property<bool>("IsDrawPile")
                        .HasColumnType("boolean")
                        .HasColumnName("Is_Draw_Pile");

                    b.HasKey("Id");

                    b.ToTable("Pile");
                });
#pragma warning restore 612, 618
        }
    }
}
